import {
  Activity,
  Archive,
  BarChart3,
  Bell,
  BellRing,
  Bot,
  BrainCircuit,
  Check,
  CheckCircle2,
  Database,
  Dna,
  Drone,
  Droplets,
  FileStack,
  FileText,
  FlaskConical,
  FolderOpen,
  Globe,
  LayoutDashboard,
  Leaf,
  Map,
  MapPin,
  Radio,
  Ruler,
  Satellite,
  Scale,
  Search,
  Settings,
  Share2,
  Sprout,
  Trees,
  TriangleAlert,
  Users,
  Waves,
  type LucideIcon,
} from 'lucide-react';

const registry: Record<string, LucideIcon> = {
  activity: Activity,
  alert: TriangleAlert,
  dashboard: LayoutDashboard,
  alerts: BellRing,
  analytics: BrainCircuit,
  archive: Archive,
  bell: Bell,
  brain: BrainCircuit,
  bot: Bot,
  chart: BarChart3,
  check: CheckCircle2,
  checkmark: Check,
  database: Database,
  dna: Dna,
  drone: Drone,
  droplets: Droplets,
  'file-stack': FileStack,
  file: FileText,
  flask: FlaskConical,
  folder: FolderOpen,
  globe: Globe,
  incidents: FolderOpen,
  leaf: Leaf,
  map: Map,
  pin: MapPin,
  radio: Radio,
  reports: FileText,
  ruler: Ruler,
  satellite: Satellite,
  scale: Scale,
  search: Search,
  settings: Settings,
  share: Share2,
  sources: Database,
  sprout: Sprout,
  trees: Trees,
  users: Users,
  vault: Archive,
  waves: Waves,
};

export function Icon({ name, ...props }: { name: string } & React.ComponentProps<LucideIcon>) {
  const Cmp = registry[name] ?? Leaf;
  return <Cmp {...props} />;
}
